DROP TABLE IF EXISTS carisa_ente_category
CREATE TABLE IF NOT EXISTS carisa_ente_category (id UUID, name text, PRIMARY KEY (id))
INSERT into carisa_ente_category(id, name) values (83ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category name')
INSERT into carisa_ente_category(id, name) values (73ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676,  'Ente Category updated')
INSERT into carisa_ente_category(id, name) values (63ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category parent')
INSERT into carisa_ente_category(id, name) values (53ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category name')
INSERT into carisa_ente_category(id, name) values (43ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category name')