DROP TABLE IF EXISTS carisa_ente_category
CREATE TABLE IF NOT EXISTS carisa_ente_category (id UUID, name text, root boolean, PRIMARY KEY (id))
INSERT into carisa_ente_category(id, name, root) values (83ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category name', false)
INSERT into carisa_ente_category(id, name, root) values (73ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category updated', false)
INSERT into carisa_ente_category(id, name, root) values (63ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category parent', false)
INSERT into carisa_ente_category(id, name, root) values (53ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category name', false)
INSERT into carisa_ente_category(id, name, root) values (43ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category name', false)
INSERT into carisa_ente_category(id, name, root) values (33ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category name', false)
INSERT into carisa_ente_category(id, name, root) values (23ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, 'Ente Category name', false)