DROP TABLE IF EXISTS carisa_ente_enteproperty
CREATE TABLE IF NOT EXISTS carisa_ente_enteproperty (enteId UUID, entePropertyId UUID, PRIMARY KEY (enteId, entePropertyId))
INSERT into carisa_ente_enteproperty(enteId, entePropertyId) values (7acdac69-fdf8-45e5-a189-2b2b4beb1c26, c0838415-6ae2-4914-b202-f1b3adbf0353)
INSERT into carisa_ente_enteproperty(enteId, entePropertyId) values (7acdac69-fdf8-45e5-a189-2b2b4beb1c26, 49ddffc7-bffe-4819-a112-e5112c1dc009)