DROP TABLE IF EXISTS carisa_ente_category_property
CREATE TABLE IF NOT EXISTS carisa_ente_category_property (parentId UUID, id UUID, name text, type int, PRIMARY KEY (parentId, id))
INSERT into carisa_ente_category_property(parentId, id, name, type) values (83ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, b9439ad1-4419-4765-acca-55ce69179c0f, 'Ente category property name', 0)
INSERT into carisa_ente_category_property(parentId, id, name, type) values (83ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, c9439ad1-4419-4765-acca-55ce69179c0f, 'Updated Ente category property', 0)
INSERT into carisa_ente_category_property(parentId, id, name, type) values (83ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, d9439ad1-4419-4765-acca-55ce69179c0f, 'Ente category property name', 1)
INSERT into carisa_ente_category_property(parentId, id, name, type) values (83ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, e9439ad1-4419-4765-acca-55ce69179c0f, 'Ente category property name', 2)
INSERT into carisa_ente_category_property(parentId, id, name, type) values (33ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, f9439ad1-4419-4765-acca-55ce69179c0f, 'Ente category property name', 1)
INSERT into carisa_ente_category_property(parentId, id, name, type) values (23ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, a9439ad1-4419-4765-acca-55ce69179c0f, 'Ente category property name', 1)
INSERT into carisa_ente_category_property(parentId, id, name, type) values (83ed3c4c-5c7f-4e76-8a2a-2e3b7bfca676, b8439ad1-4419-4765-acca-55ce69179c0f, 'Ente category property name', 1)