DROP TABLE IF EXISTS carisa_space_ente
CREATE TABLE IF NOT EXISTS carisa_space_ente (parentId UUID, enteId UUID, PRIMARY KEY (parentId, enteId))
INSERT into carisa_space_ente(parentId, enteId) values (52107f03-cf1b-4760-b2c2-4273482f0f7a, 7acdac69-fdf8-45e5-a189-2b2b4beb1c26)
INSERT into carisa_space_ente(parentId, enteId) values (52107f03-cf1b-4760-b2c2-4273482f0f7a, 8acdac69-fdf8-45e5-a189-2b2b4beb1c26)
